name: coverage
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: self-hosted

    steps:
      - name: Test with pytest
        run: |
            pytest --cov-report "xml:coverage.xml"  --cov=.
      - name: Create Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.99
            token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Coverage by coverage.py
        if: ${{ github.event_name == 'pull_request' }}
        # coverage xml coverage1.xml *.py   
        run: |
            coverage run -a -m pytest --cov-report "xml:coverage1.xml" --cov=.
      - uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage1.xml
            thresholdAll: 0.99
            token: ${{ secrets.GITHUB_TOKEN }}