name: coverage
on:
  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: self-hosted

    steps:
      - name: Test with pytest
        run: |
            pytest --cov-report "xml:coverage.xml"  --cov=.
      - name: Create Coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: orgoro/coverage@v3
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Coverage by coverage.py
        if: ${{ github.event_name == 'pull_request' }}
        # coverage xml -o coverage.xml
        run: |
            coverage run -m pytest --cov-report "xml:coverage1.xml"  --cov=.
      - uses: orgoro/coverage@v3
        with:
            coverageFile: coverage1.xml
            token: ${{ secrets.GITHUB_TOKEN }}