name: deploy
on:
  push:
  # pull_request:

  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      # contents: read
      # packages: write
      # attestations: write
      # pages: write
      # id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t lf477/tests-python .
      
    - name: Push image to Docker Hub
      run: docker push lf477/tests-python
      
    - name: Run tests in Docker container
      run: docker run lf477/tests-python