name: docker
on:
  push:
  pull_request:

  workflow_dispatch:


jobs:
  docker:
    runs-on: self-hosted
    container: composer:latest
    image: composer:latest
    volumes:
      - ${{ github.workspace }}:/app
  step:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run composer install
      run: composer install

    - name: Run tests
      run: python -m unittest test_*.py